# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.
  # when you have a couple writings you need to get tags going on
main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: post/
    weight: 20
